# Generated by Django 3.1.1 on 2020-10-01 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_auto_20181029_2313'),
        ('funcionarios', '0003_auto_20200929_1913'),
    ]

    operations = [
    ]
