# Generated by Django 3.1.1 on 2020-10-01 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_merge_20200930_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='empresas',
        ),
    ]
